
development:
 adapter: postgresql
 encoding: unicode
 database: trumpdebt_development
 pool: 5
 username: <%= Rails.application.credentials.postgres[:username] %>
 password: <%= Rails.application.credentials.postgres[:password] %>


test:
 adapter: postgresql
 encoding: unicode
 database: trumpdebt_test
 pool: 5
 username: <%= Rails.application.credentials.postgres[:username] %>
 password: <%= Rails.application.credentials.postgres[:password] %>

production:
 adapter: postgresql
 encoding: unicode
 pool: 5
 database: trumpdebt_production
 username: <%= Rails.application.credentials.postgres[:username] %>
 password: <%= Rails.application.credentials.postgres[:password] %>
