
development:
 adapter: postgresql
 encoding: unicode
 database: barrpetition_development
 pool: 5
 username: <%= Rails.application.credentials.postgres[:username] %>
 password: <%= Rails.application.credentials.postgres[:password] %>


test:
 adapter: postgresql
 encoding: unicode
 database: barrpetition_test
 pool: 5
 username: <%= Rails.application.credentials.postgres[:username] %>
 password: <%= Rails.application.credentials.postgres[:password] %>

production:
 adapter: postgresql
 encoding: unicode
 pool: 5
   <% if Rails.application.secrets[:database].present? %>
 database: barrpetition_production
 username: <%= Rails.application.credentials.postgres[:username] %>
 password: <%= Rails.application.credentials.postgres[:password] %>
<% end %>
