
development:
 adapter: postgresql
 encoding: unicode
 database: barrpetition_development
 pool: 5
 username:
 password:


test:
 adapter: postgresql
 encoding: unicode
 database: barrpetition_test
 pool: 5
 username:
 password:

production:
 adapter: postgresql
 encoding: unicode
 pool: 5
 database: barrpetition_production
 username: <%= Rails.application.credentials.postgres[:username] %>
 password: <%= Rails.application.credentials.postgres[:password] %>
